### ISSUE TITLE
using ReverseDiffSource doesn't work any more?

### ISSUE THREAD

**Issue by ulzegasi** [JuliaDiff/ReverseDiffSource.jl#15]
Hi, I've just run a Pkg.update() and now using ReverseDiffSource gives the error below.
Can anyone help?
Thank you very much!

In  [2]: using ReverseDiffSource

Out [2]: ERROR: syntax: missing comma or ) in argument list
while loading C:\Users\ulzegasi\.julia\v0.3\ReverseDiffSource\src\tograph.jl, in expression starting on line 237
while loading C:\Users\ulzegasi\.julia\v0.3\ReverseDiffSource\src\ReverseDiffSource.jl, in expression starting on line 46
while loading In[2], in expression starting on line 1

 in include at boot.jl:245
 in include_from_node1 at loading.jl:128

**Comment by fredo-dedup** [comment]
Hi @ulzegasi. I'll take a look. 

Does the error also appears with Julia 0.4 ?

**Comment by ulzegasi** [comment]
Hi @fredo-dedup 
I've realized that I was working with an old Julia version (0.3.0 if I remember correctly). I have upgraded to Julia 0.3.9 and the error has disappeared.
Thank you very much for your reply anyway!
