### ISSUE TITLE
Handle rational numbers

### ISSUE THREAD

**Issue by eschnett** [JuliaDiff/ReverseDiffSource.jl#21]
I see that e.g.
```
rdiff(:(1//2*x^2), x=1//1)
```
results in the output
```
quote 
    (1//2 * x ^ 2,2 * (x * 0.5))
end
```
which introduces the `Float64` number `0.5` instead of the rational number `1//2`.

Would this be difficult to change? Can you give me a pointer to where to look?

**Comment by fredo-dedup** [comment]
I presume that at the graph simplification stage, a `1 * 1//2` is evaluated to the Float `0.5` at some point.
When I neutralize the constant expression evaluation (function `evalconstants` in `simplify.jl`) I get:
```
quote 
    _tmp1 = 1 // 2
    (_tmp1 * x^2,2 * (x^(2 - 1) * _tmp1))
end
```
I preserve the rationals now, but I get a useless `(2-1)`. => I need more sophisticated rules to decide what should be evaluated and what should not.

**Comment by fredo-dedup** [comment]
Closing as this is a rather old issue for which there is no clear desirable solution (how should we simplify formulas mixing rationals and reals ? ).
+ this domain is not the main focus of the package
