### ISSUE TITLE
no rule for differentiating a+b+c

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDiff/ReverseDiffSource.jl#25]
Differentiating  `x + y + z` does not work, but  `(x + y) + z` is okay
```julia
function foo(x,y,z)
    return x + y + z
end
rdiff(foo,(1,1,1))
ERROR: no derivation rule for + at arg #1 for signature Tuple{Int64,Int64,Int64}

function foo(x,y,z)
    return (x + y) + z
end

rdiff(foo,(1,1,1))
```

**Comment by fredo-dedup** [comment]
n-ary operations, with n > 2, are supposed to be broken down into binary ops automatically by `ReverseDiffSource`. It does work with expressions but not anymore with functions. It is probably caused by a change in the AST format produced by Julia.
This is a bug, I'll look into it.

**Comment by fredo-dedup** [comment]
Corrected in latest commit in master.
