### ISSUE TITLE
Tests fail after latest commit (and metadata)

### ISSUE THREAD

**Issue by scidom** [JuliaDiff/ReverseDiffSource.jl#30]
Hi @fredo-dedup, thanks for pushing the latest fixes to master. I have noticed that the tests now fail after the last commit, which probably causes a failure of tests in Lora too. Is the source of error easy to fix or is it a more troubling bug? If it is an easy matter to sort out, we may make sure that the the build errors are fixed and push the latest ReverseDiffSource to metadata (and I can then do the same for Lora).

**Comment by fredo-dedup** [comment]
I found that the breaking change #13612 in Julia v0.5 (dropping dimensions indexed by a scalar) caused an error in the `show` function for graph types used in `ReverseDiffSource`.
Tests now pass in both 0.4 and nightly and I tagged a new version 0.2.1 (PR pending)

**Comment by scidom** [comment]
Thanks a lot Frédéric, once your PR is merged by the metadata maintainers, I will make sure Lora passes the tests too, and by next week (once I complete the nearly finished Gibbs job), I will tag a new Lora release too.
