### ISSUE TITLE
Possible bug related to allorders option

### ISSUE THREAD

**Issue by scidom** [JuliaDiff/ReverseDiffSource.jl#32]
Hi @fredo-dedup, I think I found a small bug (though not 100% sure). 

```
julia> rdiff( :(y*x^3+y^5) , x=2., y=1., order=1)
quote 
    _tmp1 = x ^ 3
    (y * _tmp1 + y ^ 5,3 * (x ^ 2 * y),_tmp1 + 5 * y ^ 4)
end

julia> rdiff( :(y*x^3+y^5) , x=2., y=1., order=1, allorders=false)
quote 
    5 * y ^ 4 + x ^ 3
end
```

In both cases first order derivatives are generated. However, the presence of the `allorder=false` option seems to produce only the first order partial derivative with respect to `y` (but not with respect to `x`), which I think shouldn't happen.

This is not critical, I can carry on with the developments in Lora, but I thought it would be worth reporting it.

**Comment by fredo-dedup** [comment]
Corrected in latest master

**Comment by scidom** [comment]
Thanks @fredo-dedup!
