### ISSUE TITLE
Reverse AD for mod2pi()

### ISSUE THREAD

**Issue by scidom** [JuliaDiff/ReverseDiffSource.jl#34]
Hi @fredo-dedup , how easy would it be to implement reverse AD for  the `mod2pi()` function? @eford, a collaborator, would like to make use of such functionality. Would it be possible to help with this? I don't know much about the internals of ReverseDiffSource (I only use its interface to integrate it with Lora), so it would either be you who implements it or you could give me some directions and I can try to contribute a PR :+1:

**Comment by fredo-dedup** [comment]
This should do : 
```julia
@deriv_rule mod2pi(x::Real) x ds 
```
(since the derivative is always 1. ).

**Comment by scidom** [comment]
Thanks @fredo-dedup! I will open a PR later on today about this.

**Comment by scidom** [comment]
I will close this issue now, as I have opened a PR for mod2pi().
