### ISSUE TITLE
__precompile__(false)

### ISSUE THREAD

**Issue by jeff-regier** [JuliaDiff/ReverseDiffSource.jl#37]
Any plans to support precompilation in ReverseDiffSource?

**Comment by fredo-dedup** [comment]
I tried but it turned out to not work properly (possibly because of the derivation rules dictionary which is indexed by a Function). But it is certainly doable.

I'll tag this as an enhancement.

Are you facing a context in which this is a big issue ?

**Comment by jeff-regier** [comment]
Thanks for looking into it! Over at [Celeste.jl](https://github.com/jeff-regier/Celeste.jl) we'd like to use ReverseDiffSource for all the derivatives we're computing manually now (e.g., [ElboDeriv.jl](https://github.com/jeff-regier/Celeste.jl/blob/master/src/ElboDeriv.jl) . Without precompilation, however, `using ReverseDiffSource` and calling rdiff the first time takes about 30 seconds. Since we're deploying this across a lot of nodes on a supercomputer, it would add up to quite a bit of extra runtime.

**Comment by fredo-dedup** [comment]
version v0.3.0 adds precompilation (and julia v0.5 compatibility) => closing

Please reopen if pre-compilation still has issues.
