### ISSUE TITLE
Derivatives of a function inside another functions

### ISSUE THREAD

**Issue by dfdx** [JuliaDiff/ReverseDiffSource.jl#38]
As far as I understand, currently it's not possible to calculate derivative of a user-defined function inside another function, e.g.:

```
using ReverseDiffSource

foo(x::Vector) = sum(x .* x)
dfoo = rdiff(foo, (rand(5),))
dfoo(rand(5))  # ==> (0.940462225724767,[1.01...])

bar(x::Vector) =  foo(x) + 1
dbar = rdiff(bar, (rand(5),))  # ERROR: no derivation rule for foo at arg #1
```

How hard it would be to implement such a feature? I see that `rdiff(::Function,...)` calls `rdiff(::Expr,...)`, does it make sense for `rdiff(::Expr,...)` to call back `rdiff(::Function)` or something like that?

**Comment by fredo-dedup** [comment]
There is not any fundamental obstacle that I can see but the implementation details could be really complicated (how to deal with recursive calls for instance ?).
How about calling rdiff on the expression form of the inner function and defining the derivation rule with `@deriv-rule foo(x) x <expr>`  ?
Would that fit in your workflow ?

**Comment by dfdx** [comment]
Using `@deriv_rule` is a bit manual, but may work for me, so I'll give it a try. Thanks!

Supporting recursive functions is an interesting task by itself, though. I see this package supports `for` loops which is somewhat similar to recursion, but understanding that part of the code is a bit complicated for me. Would you mind giving a short high-level description of how you handle it?
