### ISSUE TITLE
rdiff() (devl3) with Hamiltonian Monte Carlo (HMC)?

### ISSUE THREAD

**Issue by carloalbert** [JuliaDiff/ReverseDiffSource.jl#4]
rdiff(), from branch devl3, does an excellent job for me! Thanks!
But now, I want to use it within a HMC algorithm. Currently, ReverseDiffSource from devl3, does not work together with the MCMC package:
Pkg.checkout("ReverseDiffSource", "devl3") leads to build errors in GraphViz. 
Any estimates as to when it will work with MCMC? Or recommendations for other implementations of HMC?
Thanks a lot!

**Comment by fredo-dedup** [comment]
This is being adressed in on-going developments in Lora (the successor to MCMC). Closing because not strictly related to ReverseDiffSource.
