### ISSUE TITLE
Possible indexing issue upon v0.5 upgrade

### ISSUE THREAD

**Issue by scidom** [JuliaDiff/ReverseDiffSource.jl#42]
Hi Frederic, I hope you are well. I have tried to upgrade Lora to work with Julia v0.5. One error that came up, related to ReverseDiffSource, is the following:

```
ERROR: MethodError: no method matching getindex(::Base.MethodList, ::Int64)
 in #rdiff#135(::Array{Any,1}, ::Function, ::Function, ::Tuple{Array{Float64,1}}) at /Users/theodore/.julia/v0.5/ReverseDiffSource/src/frdiff.jl:38
```

I know I haven't provided enough context, yet you might be able to see quicker than me what is the issue with line 38, `fdef = fs[1].func`, in src/frdiff.jl.

**Comment by dfdx** [comment]
The goal of the code you mentioned is to extract AST and arguments of a function to be differentiated. Recently internal function representation has been changed and ReverseDiffSource.jl hasn't been updated to reflect it yet. For my own package I managed to overcome this issue using [this piece of code](https://github.com/dfdx/Espresso.jl/blob/stabilization/src/funexpr.jl#L49-L61) but I currently don't have time to port it back to ReverseDiffSource.jl. If it's urgent for you, you may port it yourself or ping me in ~1 week when I have a bit more time.

**Comment by scidom** [comment]
Thanks, @dfdx, I can wait till this gets sorted, it is not so urgent for me. I am still using Julia v0.4.6, because the changes in v0.5 and non-supressed warnings across various packages make it difficult to work with. I will wait till the ecosystem catches up with v0.5.

**Comment by dfdx** [comment]
@scidom I've updated the code for Julia 0.5 including a fix for your feature and it's available in my [support-v0.5](https://github.com/dfdx/ReverseDiffSource.jl/tree/support-v0.5) branch. However, I encountered an issue as in #41 with Julia 0.5-rc2. As it's mentioned in that issue, code should work with some development version of Julia itself, so you can try it. Alternatively, I'd suggest to just wait until Julia gets a stable 0.5 tag and then switch to it.

**Comment by scidom** [comment]
Thanks a lot @dfdx. I don't mind waiting till Julia gets a stable 0.5 tag, as I am busy anyhow with other computing matters right now.

**Comment by fredo-dedup** [comment]
I have branch (inference) that is not merged yet to master, but it works with julia 0,5. As a bonus, it uses types instead of values as input (check the embedded doc) which should simplify things for Klara.
Will keep you updated when it is tagged.

**Comment by scidom** [comment]
Thanks @fredo-dedup, this is great. Yes, keep me posted once ready, and I will then update Klara's glue code for calling the reverse diff routines appropriately.

**Comment by fredo-dedup** [comment]
Done. Check out version v0.3.0.
Do not hesitate to post here any issue you encounter. Thanks.
