### ISSUE TITLE
Error when differentiating with order=0

### ISSUE THREAD

**Issue by scidom** [JuliaDiff/ReverseDiffSource.jl#48]
Hi @fredo-dedup, I am trying to upgrade Klara to work with the ReverseDiffSource updates. The following breaks:

```
rdiff(:(dot(z, z)), z=Vector{Float64}, order=0)
```

returning

```
ERROR: [rdiff] inconsistent parameters
 in #rdiff#125(::Void, ::Int64, ::Module, ::Bool, ::Bool, ::Array{Symbol,1}, ::Array{Any,1}, ::Function, ::Expr) at /Users/theodore/.julia/v0.5/ReverseDiffSource/src/rdiff.jl:266
 in (::ReverseDiffSource.#kw##rdiff)(::Array{Any,1}, ::ReverseDiffSource.#rdiff, ::Expr) at ./<missing>:0
```

If this is easy to fix, it would be easy to push a new minor version of ReverseDiffSource on metadata.

**Comment by fredo-dedup** [comment]
This should be corrected on master now.

I will tag it later. I am keeping this open until you tell me it is working for you.

**Comment by papamarkou** [comment]
This is really great @fredo-dedup, it fixed the issue. There was only one example in Klara's README that was failing, but after your fix, it's all fine.
